on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: [self-hosted, aws]
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - run: aws s3 ls
    # - uses: Azure/docker-login@v1
    #   with:
    #     login-server: mycontainer.azurecr.io
    #     username: ${{ steps.myGetSecretAction.outputs.adesuwarsecretkey}}
    #     password: ${{ steps.myGetSecretAction.outputs.adesuwaraccesskey }}
    
        
 

 


